### ISSUE TITLE
signal stops when calling from javascript

### ISSUE THREAD

**Issue by gerardklee** [OpenBCI/OpenBCI_NodeJS_Wifi#33]
Hello,

As soon as I call the javascript function to start streaming, the signals on GUI completely stops. I am new to javascript, so I don't know if this is my code issue or the wifi shield issue. Attached is my block of code to get the data from the board. I would appreciate any help!
I am using macOS Mojave 10.14.6, OpenBCI_GUI 4.1.5

Thank you.

<img width="305" alt="Screen Shot 2020-01-09 at 2 11 48 PM" src="https://user-images.githubusercontent.com/47463934/72109113-01134e80-32ea-11ea-9ca7-51d1db31dded.png">

**Comment by gerardklee** [comment]
I wanted to add that streaming works perfectly fine with matlab.

**Comment by Andrey1994** [comment]
I suppose you try to start streaming data from a board to openbci gui and to your js code at the same time. But it will never work as you expect because board sends data via tcp/udp socket without broadcast/multicast so there can be only one receiver.

If you need the same data in the GUI and in your JS code you should read data directly from a board in the GUI and stream it further using GUI networking widget but this SDK doesnt read data from networking widget this SDK reads data from a board. So you will need to write a code to receive it from scratch

**Comment by gerardklee** [comment]
Would you kindly briefly tell me how I can implement receiving the data? Are there JS libraries for signal processing or anything for getting the data from OpenBCI type of GUI? When you say I have to write from 'scratch', does it mean I won't be able to use any JS signal processing libraries? Sorry for asking too many questions, but I really appreciate your help!

**Comment by Andrey1994** [comment]
Try to use this sdk without GUI first so there will be only one data receiver.

If you wanna stream data from the GUI you can try js bunding for LSL or stream data via socket and read data from socket.

This lib has no signal processing algorithms its only for data acquisition, if JS is not crucial for you I would recommend to use brainflow instead https://brainflow.readthedocs.io/en/stable/
Currently there is no JS binding but there are signal processing API and many other languages. And I will add JS and julia later.

**Comment by gerardklee** [comment]
Thank you, @Andrey1994 . Your advice helped a lot!
